apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcpcoder.authFullname" . }}-tokens
  labels:
    {{- include "mcpcoder.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokens: |
    {{- range .Values.auth.tokens }}
    {{ . }}
    {{- end }}
