apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcpcoder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snothub/skillz.git
    targetRevision: main
    path: helm/mcpcoder
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mcpcoder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
